import type { CompetitiveMovesData } from "../../types/sections";

// Generated by scripts/etl-v1-to-v2-mocks.mjs — 2026-02-22
// Source: consumer-durables-intelligence/assets/js/data.js

const data: CompetitiveMovesData = {
  "section": "competitive-moves",
  "dataAsOf": "Q3 FY26",
  "lastUpdated": "2026-02-22T00:00:00Z",
  "productLaunches": [
    {
      "company": "Voltas",
      "product": "Flo Series BLDC ceiling fans launched",
      "category": "Fans",
      "positioningNote": "Category expansion into ceiling fans with energy-efficient BLDC-motor Flo Series, competing with Crompton, Havells, Orient.",
      "date": "2025-07-01"
    },
    {
      "company": "Voltas",
      "product": "PLI scheme Round 3 applicant — white goods",
      "category": "Lighting & Electricals",
      "positioningNote": "Among 38 applicants in 3rd round of PLI scheme for white goods (ACs & LED lights).",
      "date": "2024-10-14"
    },
    {
      "company": "Voltas",
      "product": "Divested 92% in Saudi Ensas — exiting non-core",
      "category": "Consumer Durables",
      "positioningNote": "Transferred 92% investment in Saudi Ensas to Universal MEP Projects Singapore for ₹61.84 Cr.",
      "date": "2025-02-01"
    },
    {
      "company": "Blue Star",
      "product": "PLI scheme Round 3 applicant — AC manufacturing",
      "category": "Air Conditioning",
      "positioningNote": "Among applicants in 3rd PLI round for AC manufacturing value chain expansion.",
      "date": "2024-10-14"
    },
    {
      "company": "Crompton Greaves Consumer",
      "product": "Zero-debt: retired ₹2,125 Cr Butterfly acquisition NCDs",
      "category": "Consumer Durables",
      "positioningNote": "Fully repaid all 5 tranches of NCDs originally issued for 2022 Butterfly acquisition. Now net cash positive.",
      "date": "2025-07-23"
    },
    {
      "company": "Bajaj Electricals",
      "product": "Bajel Projects demerger listed — ₹1,260 Cr entity",
      "category": "Consumer Durables",
      "positioningNote": "EPC/Power T&D demerged into Bajel Projects Ltd. Now pure-play consumer electricals. Shekhar Bajaj chairs both.",
      "date": "2025-02-01"
    },
    {
      "company": "V-Guard Industries",
      "product": "Sunflame Vapi factory live — kitchen appliance capacity",
      "category": "Kitchen Appliances",
      "positioningNote": "Commercial production at Vapi Gujarat factory for Sunflame kitchen appliances. Targeting 12% EBIT margin in 2-3 years.",
      "date": "2024-03-06"
    },
    {
      "company": "V-Guard Industries",
      "product": "₹20 Cr in Gegadyne Energy Labs — battery startup",
      "category": "New Energy",
      "positioningNote": "Additional investment increasing stake to 24.32%. Gegadyne became associate company. Battery tech for future product line.",
      "date": "2023-11-01"
    },
    {
      "company": "IFB Industries",
      "product": "Swiss subsidiary Schmid GmbH — European design facility",
      "category": "Consumer Durables",
      "positioningNote": "Established Schmid Automotive & Appliances GmbH in Switzerland for design and tooling capabilities.",
      "date": "2024-11-01"
    },
    {
      "company": "IFB Industries",
      "product": "₹97 Cr in IFB Refrigeration — Ranjangaon plant",
      "category": "Home Appliances",
      "positioningNote": "₹97 Cr for ~41.4% stake in IFB Refrigeration Limited. Trial production commenced at Pune facility.",
      "date": "2023-05-01"
    },
    {
      "company": "Havells India",
      "product": "₹480 Cr refrigerator plant at Ghiloth Rajasthan",
      "category": "Home Appliances",
      "positioningNote": "New Lloyd refrigerator manufacturing — 14 lakh unit capacity. Operational Q2 FY27. Internally funded.",
      "date": "2024-11-01"
    },
    {
      "company": "Havells India",
      "product": "₹715 Cr cable expansion at Alwar — two phases",
      "category": "Cables & Wires",
      "positioningNote": "Cable capacity from 32.9L km to 41.45L km. Phase 1: ₹375 Cr (Jul 2024), Phase 2: ₹340 Cr (May 2025). Internal accruals.",
      "date": "2025-05-01"
    },
    {
      "company": "Havells India",
      "product": "YEIDA Electronics Manufacturing Cluster — ₹800 Cr",
      "category": "Consumer Durables",
      "positioningNote": "Anchor investor in 200-acre EMC. 50-acre land. Phase-1 ₹800 Cr. MeitY approved Apr 2025.",
      "date": "2025-04-25"
    },
    {
      "company": "Havells India",
      "product": "₹600 Cr in Goldi Solar — 8.9% strategic stake",
      "category": "New Energy",
      "positioningNote": "Investment in solar module manufacturer as part of ₹1,300 Cr fundraise. Renewable energy diversification.",
      "date": "2025-04-01"
    },
    {
      "company": "Havells India",
      "product": "Lloyd Kolors Refrigerator — Flipkart exclusive",
      "category": "Home Appliances",
      "positioningNote": "Smart refrigerator with Auto Defrost, Inverter Compressor. Exclusive e-commerce launch. Premium white goods play.",
      "date": "2025-09-01"
    },
    {
      "company": "Symphony",
      "product": "Australia + Mexico divestiture plans shelved",
      "category": "Consumer Durables",
      "positioningNote": "Explored selling Climate Technologies Australia (neg. EBITDA) and IMPCO Mexico. Shelved — no buyers at valuation.",
      "date": "2025-04-01"
    },
    {
      "company": "Orient Electric",
      "product": "CK Birla sells Orient Cement (₹8,100 Cr) — capital to consumer",
      "category": "Consumer Durables",
      "positioningNote": "Parent sold 46.8% Orient Cement to Ambuja Cements (Adani) for ₹8,100 Cr. Capital reallocated to consumer businesses.",
      "date": "2024-10-22"
    },
    {
      "company": "Dixon Technologies",
      "product": "50.1% in Ismartu India (Transsion brands) — ₹275 Cr",
      "category": "Smart Home",
      "positioningNote": "Acquired manufacturer for Itel, Infinix, Tecno brands. CCI approved. Tranche 2 based on FY26 PAT.",
      "date": "2024-08-01"
    },
    {
      "company": "Dixon Technologies",
      "product": "JV with Vivo India (51:49) — smartphone OEM",
      "category": "Smart Home",
      "positioningNote": "Binding term sheet for JV to manufacture electronic devices including smartphones. Pending regulatory approval.",
      "date": "2024-12-16"
    },
    {
      "company": "Dixon Technologies",
      "product": "JV with Signify (Philips) — lighting OEM",
      "category": "Lighting & Electricals",
      "positioningNote": "JV for OEM business of lighting products and accessories in India.",
      "date": "2025-04-01"
    },
    {
      "company": "Dixon Technologies",
      "product": "$2.7-3B display fab facility in Noida",
      "category": "Consumer Durables",
      "positioningNote": "8.6G display fabrication with HKC (China). 60K substrates/month. India Semiconductor Mission incentives.",
      "date": "2025-06-01"
    },
    {
      "company": "Amber Enterprises",
      "product": "Acquiring Shogini Technoarts — top 5 PCB maker",
      "category": "Consumer Durables",
      "positioningNote": "ILJIN subsidiary acquiring majority stake. Pune-based, ₹390.74 Cr FY25 revenue.",
      "date": "2025-11-15"
    },
    {
      "company": "Amber Enterprises",
      "product": "40.2% controlling stake in Israel's Unitronics — ₹404 Cr",
      "category": "Smart Home",
      "positioningNote": "ILJIN acquired controlling stake for building automation/industrial IoT. Together holds ~45.13%.",
      "date": "2025-07-28"
    },
    {
      "company": "Amber Enterprises",
      "product": "60% in Power-One Micro — BESS, solar, EV chargers",
      "category": "New Energy",
      "positioningNote": "ILJIN acquired 60% for ₹262 Cr. Battery energy storage, solar inverters, EV charger manufacturing.",
      "date": "2025-06-01"
    },
    {
      "company": "Amber Enterprises",
      "product": "₹1,200 Cr PE raise for ILJIN — ChrysCapital leads",
      "category": "Consumer Durables",
      "positioningNote": "ChrysCapital, Two Infinity Partners, Raptor, InCred Growth Partners backed subsidiary expansion.",
      "date": "2025-09-07"
    },
    {
      "company": "TTK Prestige",
      "product": "₹500 Cr 3-year capex — stainless steel + automation",
      "category": "Consumer Durables",
      "positioningNote": "₹300 Cr capex (tri-ply, appliances, modernization) + ₹200 Cr operational investments. Internal accruals.",
      "date": "2025-02-19"
    },
    {
      "company": "TTK Prestige",
      "product": "GramyaHaat rural distribution — ₹15 Cr investment",
      "category": "Consumer Durables",
      "positioningNote": "Up to ₹15 Cr in rural distribution tech platform via CCDs for >5% equity.",
      "date": "2024-06-12"
    },
    {
      "company": "Bosch Home Comfort (JCHAC)",
      "product": "Bosch acquires 74.2% — $8.1B global deal completes",
      "category": "Consumer Durables",
      "positioningNote": "Largest deal in Bosch history. Open offer for remaining 25.75%. Post-offer holding ~82.22%.",
      "date": "2025-08-01"
    },
    {
      "company": "Bosch Home Comfort (JCHAC)",
      "product": "Rebranded JCHAC → Bosch Home Comfort India",
      "category": "Consumer Durables",
      "positioningNote": "Company renamed, stock symbol changed from JCHAC to BOSCH-HCIL.",
      "date": "2025-12-24"
    },
    {
      "company": "Butterfly Gandhimathi",
      "product": "Shareholders reject Crompton merger — 72.6% against",
      "category": "Consumer Durables",
      "positioningNote": "Public shareholders voted 72.61% against merger. Non-institutional investors 97% against. Companies continue independently.",
      "date": "2023-11-01"
    },
    {
      "company": "Butterfly Gandhimathi",
      "product": "Brand refresh — \"Celebrating Change\" identity",
      "category": "Consumer Durables",
      "positioningNote": "New brand identity with fingerprint-butterfly logo. Refreshed positioning targeting self-aware consumers. Part of Crompton ecosystem.",
      "date": "2025-06-23"
    },
    {
      "company": "Bajaj Electricals",
      "product": "Bajaj Secura Wires — new business line launch",
      "category": "Cables & Wires",
      "positioningNote": "Entered wires category under Lighting Solutions segment. High-performance residential wiring solutions with advanced technology. Diversification play.",
      "date": "2026-01-20"
    },
    {
      "company": "Bajaj Electricals",
      "product": "Entry into Solar Solutions business",
      "category": "Lighting & Electricals",
      "positioningNote": "Board approved Solar Solutions as new line under Lighting segment. Investment TBD based on market assessment.",
      "date": "2025-12-17"
    },
    {
      "company": "Bajaj Electricals",
      "product": "Switchgear range launch — MCBs, RCCBs, isolators",
      "category": "Cables & Wires",
      "positioningNote": "Launched MCBs, RCCBs, isolators, changeover switches, distribution boards for domestic market. Safety and precision positioning.",
      "date": "2025-08-07"
    },
    {
      "company": "Bajaj Electricals",
      "product": "Smart lighting co-development with IIT Bombay",
      "category": "Lighting & Electricals",
      "positioningNote": "Partnered with TIH Foundation at IIT Bombay for smart lighting solutions. Smart city focus, aligning with Digital India initiative.",
      "date": "2025-10-16"
    },
    {
      "company": "Blue Star",
      "product": "150 new Room AC models — Smart WiFi & Heavy Duty",
      "category": "Air Conditioning",
      "positioningNote": "Launched 150 models across inverter, fixed speed, and window ACs. Focus on Smart WiFi and Heavy Duty segments at varied price points.",
      "date": "2025-02-25"
    },
    {
      "company": "Blue Star",
      "product": "New assembly line at Sri City plant",
      "category": "Air Conditioning",
      "positioningNote": "Commissioned new Room AC assembly line at Sri City through subsidiary Blue Star Climatech Limited. Capacity expansion.",
      "date": "2025-02-25"
    },
    {
      "company": "Havells India",
      "product": "EV Charger (EVSE) business launch — ₹7-10 Cr investment",
      "category": "New Energy",
      "positioningNote": "Entered EV charging market. ₹7-10 Cr investment, estimated market ₹1,500 Cr. Operations by Q3 FY26.",
      "date": "2025-05-21"
    },
    {
      "company": "Havells India",
      "product": "Lloyd Luxuria Collection — premium AC, TV, washing machine",
      "category": "Air Conditioning",
      "positioningNote": "Unveiled StunnAir, Stellar, Stylus AC lines, Mini LED TV, Novante Washing Machine. Capacity increased to 3M ACs. Premium segment push.",
      "date": "2025-04-07"
    },
    {
      "company": "Dixon Technologies",
      "product": "JV with Inventec Corporation — Notebook PCs & Servers",
      "category": "Consumer Durables",
      "positioningNote": "Dixon 60% (₹20.51 Cr), Inventec 40% (₹13.68 Cr). Manufacturing notebook PCs, servers, desktops and components in India.",
      "date": "2025-10-18"
    },
    {
      "company": "Dixon Technologies",
      "product": "Google Pixel smartphone manufacturing — Padget Electronics",
      "category": "Smart Home",
      "positioningNote": "Subsidiary Padget Electronics to mass-produce Google Pixel smartphones at Noida plant. Landmark tech manufacturing deal.",
      "date": "2025-01-01"
    },
    {
      "company": "Symphony",
      "product": "Water heater SKU expansion — new growth vertical",
      "category": "Air Conditioning",
      "positioningNote": "Launched new SKUs in water heaters alongside air cooler innovations. Expanding into high-margin growth markets beyond cooling.",
      "date": "2025-12-01"
    }
  ],
  "pricingActions": [
    {
      "company": "Whirlpool of India",
      "action": "decrease",
      "category": "Consumer Durables",
      "magnitudePct": 11.23,
      "context": "Whirlpool Corp sold 11.23% at ₹1,030/share (14% discount) raising ₹1,489 Cr. Holding now ~39.77%, targeting ~20%."
    },
    {
      "company": "Whirlpool of India",
      "action": "increase",
      "category": "Consumer Durables",
      "magnitudePct": 57,
      "context": "Advent International exclusive talks for 57% controlling stake (~$1B). Collapsed Dec 2025 over pricing disagreements."
    }
  ],
  "d2cInitiatives": [],
  "qcPartnerships": [],
  "clusterAnalysis": [
    {
      "cluster": "Premium Innovators",
      "companies": [
        "Havells India",
        "Blue Star Limited",
        "TTK Prestige Limited"
      ],
      "characteristics": "Premium brand positioning, high R&D spend, >30% premium product mix, strong D2C channels",
      "outlook": "Well-positioned for premiumization trend. Margin expansion through mix shift. Risk: premium demand elasticity in downturn."
    },
    {
      "cluster": "Scale Manufacturers (OEM/ODM)",
      "companies": [
        "Dixon Technologies",
        "Amber Enterprises",
        "Johnson Controls-Hitachi"
      ],
      "characteristics": "Contract manufacturing, PLI beneficiaries, B2B model, capacity-driven growth",
      "outlook": "Volume growth from PLI and import substitution. Margin risk from commodity pass-through. Amber expanding into components."
    },
    {
      "cluster": "Mass-Market Electricals",
      "companies": [
        "Crompton Greaves",
        "Bajaj Electricals",
        "V-Guard Industries",
        "Orient Electric"
      ],
      "characteristics": "GT-heavy distribution, mass-market pricing, fan/lighting/small appliance focus",
      "outlook": "Consolidation ongoing (Crompton-Butterfly, V-Guard-Sunflame). Premium fan shift is key margin lever. Rural recovery needed for volume growth."
    },
    {
      "cluster": "Turnaround Candidates",
      "companies": [
        "IFB Industries",
        "Butterfly Gandhimathi",
        "Symphony Limited"
      ],
      "characteristics": "Governance/financial stress signals, sub-sector leadership but operational challenges",
      "outlook": "IFB: auditor flags + board concerns. Butterfly: negative OCF. Symphony: international losses. All need operational turnaround before growth reinvestment."
    }
  ]
};

export default data;
