import type { DealsTransactionsData } from "../../types/sections";

// Generated by scripts/etl-v1-to-v2-mocks.mjs — 2026-02-22
// Source: consumer-durables-intelligence/assets/js/data.js

const data: DealsTransactionsData = {
  "section": "deals-transactions",
  "dataAsOf": "Q3 FY26",
  "lastUpdated": "2026-02-22T00:00:00Z",
  "deals": [
    {
      "id": "deal-001",
      "type": "M&A",
      "parties": [
        "Whirlpool of India",
        "SBI MF / Aditya Birla Sunlife MF / Societe Generale"
      ],
      "valueCr": 3800,
      "rationale": "Whirlpool Corp sold 24% stake in Indian unit via block deal, reducing holding from 75% to 51%. Goldman Sachs advised.",
      "date": "2024-02-20",
      "source": "BusinessToday",
      "amAngle": "Valuation",
      "amAngleRationale": "Whirlpool Corp sold 24% stake in Indian unit via block deal, reducing holding from 75% to 51%. Goldman Sachs advised."
    },
    {
      "id": "deal-002",
      "type": "M&A",
      "parties": [
        "Whirlpool of India",
        "Reliance Retail / Havells / EQT / Bain Capital (bidders)"
      ],
      "valueCr": null,
      "rationale": "Multiple bidders entered race for 31% controlling stake. Havells, EQT, Bain all subsequently withdrew over valuation.",
      "date": "2025-07-23",
      "source": "Business Standard",
      "amAngle": "Valuation",
      "amAngleRationale": "Multiple bidders entered race for 31% controlling stake. Havells, EQT, Bain all subsequently withdrew over valuation."
    },
    {
      "id": "deal-003",
      "type": "M&A",
      "parties": [
        "Whirlpool of India",
        "Advent International"
      ],
      "valueCr": 8500,
      "rationale": "Advent entered exclusive talks to buy 57% controlling stake (31% direct + 26% open offer). Deal collapsed Dec 2025 over pricing disagreements.",
      "date": "2025-12-06",
      "source": "Business Standard",
      "amAngle": "Restructuring",
      "amAngleRationale": "Advent entered exclusive talks to buy 57% controlling stake (31% direct + 26% open offer). Deal collapsed Dec 2025 over…"
    },
    {
      "id": "deal-004",
      "type": "M&A",
      "parties": [
        "Whirlpool of India",
        "HDFC MF / Kotak MF / Franklin Templeton / ICICI Pru Life / Societe Generale / East Bridge Capital"
      ],
      "valueCr": 1490,
      "rationale": "Whirlpool Mauritius sold 1.42 Cr shares (11.23% stake) via bulk deal at ₹1,045/share.",
      "date": "2025-11-27",
      "source": "Outlook Business",
      "amAngle": "Valuation",
      "amAngleRationale": "Whirlpool Mauritius sold 1.42 Cr shares (11.23% stake) via bulk deal at ₹1,045/share."
    },
    {
      "id": "deal-005",
      "type": "M&A",
      "parties": [
        "Voltas",
        "Universal MEP Projects Singapore"
      ],
      "valueCr": 62,
      "rationale": "Voltas completed transfer of 92% direct investment in Saudi Ensas Company for Engineering Services to Universal MEP Projects.",
      "date": "2025-02-28",
      "source": "Voltas Annual Report",
      "amAngle": "Carve-out Advisory",
      "amAngleRationale": "Voltas completed transfer of 92% direct investment in Saudi Ensas Company for Engineering Services to Universal MEP…"
    },
    {
      "id": "deal-006",
      "type": "PE/VC",
      "parties": [
        "Voltas",
        "Govt of India (DPIIT)"
      ],
      "valueCr": null,
      "rationale": "Voltas among 38 applicants in 3rd round of PLI scheme for white goods (ACs & LED lights) with proposed investment commitments.",
      "date": "2024-10-14",
      "source": "Business Standard",
      "amAngle": "Valuation",
      "amAngleRationale": "Voltas among 38 applicants in 3rd round of PLI scheme for white goods (ACs & LED lights) with proposed investment…"
    },
    {
      "id": "deal-007",
      "type": "PE/VC",
      "parties": [
        "Blue Star",
        "Govt of India (DPIIT)"
      ],
      "valueCr": null,
      "rationale": "Blue Star among 38 applicants in 3rd round of PLI scheme for white goods with committed investment proposals for AC manufacturing.",
      "date": "2024-10-14",
      "source": "Business Standard",
      "amAngle": "Valuation",
      "amAngleRationale": "Blue Star among 38 applicants in 3rd round of PLI scheme for white goods with committed investment proposals for AC…"
    },
    {
      "id": "deal-008",
      "type": "M&A",
      "parties": [
        "Crompton Greaves Consumer",
        "Crompton Greaves Consumer Electricals"
      ],
      "valueCr": null,
      "rationale": "Proposed merger of Crompton and Butterfly (swap ratio: 22 Crompton shares for 5 Butterfly). Public shareholders voted 72.61% against; 97% of non-institutional investors opposed. Merger rejected.",
      "date": "2023-10-31",
      "source": "BusinessToday",
      "amAngle": "Restructuring",
      "amAngleRationale": "Proposed merger of Crompton and Butterfly (swap ratio: 22 Crompton shares for 5 Butterfly). Public shareholders voted…"
    },
    {
      "id": "deal-009",
      "type": "PE/VC",
      "parties": [
        "Crompton Greaves Consumer",
        "NCD Holders / Lenders"
      ],
      "valueCr": 2125,
      "rationale": "Crompton fully repaid ₹2,125 Cr NCD debt (5 tranches) originally issued to fund 2022 Butterfly acquisition. Crompton becomes zero-debt, net cash positive.",
      "date": "2025-07-23",
      "source": "Business Standard",
      "amAngle": "Valuation",
      "amAngleRationale": "Crompton fully repaid ₹2,125 Cr NCD debt (5 tranches) originally issued to fund 2022 Butterfly acquisition. Crompton…"
    },
    {
      "id": "deal-010",
      "type": "M&A",
      "parties": [
        "Bajaj Electricals",
        "Bajel Projects Ltd (Resulting Company)"
      ],
      "valueCr": 1260,
      "rationale": "Bajaj Electricals demerged power T&D business into Bajel Projects Limited, valued at ₹1,260 Cr. 1 Bajel share for every 1 Bajaj Electricals share.",
      "date": "2023-09-14",
      "source": "Bajaj Electricals IR",
      "amAngle": "Carve-out Advisory",
      "amAngleRationale": "Bajaj Electricals demerged power T&D business into Bajel Projects Limited, valued at ₹1,260 Cr. 1 Bajel share for every…"
    },
    {
      "id": "deal-011",
      "type": "M&A",
      "parties": [
        "Bajaj Electricals",
        "Bajaj Electricals (60% stake holder)"
      ],
      "valueCr": null,
      "rationale": "Bajaj pursuing revival of manufacturing business of Hind Lamps Ltd (sick company since 2002 under BIFR). Scheme of arrangement requires NCLT approval.",
      "date": "2026-02-15",
      "source": "M&A Critique",
      "amAngle": "CDD Opportunity",
      "amAngleRationale": "Bajaj pursuing revival of manufacturing business of Hind Lamps Ltd (sick company since 2002 under BIFR). Scheme of…"
    },
    {
      "id": "deal-012",
      "type": "M&A",
      "parties": [
        "V-Guard Industries",
        "V-Guard Industries"
      ],
      "valueCr": 660,
      "rationale": "V-Guard completed 100% acquisition of Sunflame Enterprises (kitchen appliances) for all-cash ₹660 Cr. Sunflame became wholly-owned subsidiary.",
      "date": "2023-01-12",
      "source": "Business Standard",
      "amAngle": "CDD Opportunity",
      "amAngleRationale": "V-Guard completed 100% acquisition of Sunflame Enterprises (kitchen appliances) for all-cash ₹660 Cr. Sunflame became…"
    },
    {
      "id": "deal-013",
      "type": "PE/VC",
      "parties": [
        "V-Guard Industries",
        "V-Guard Industries"
      ],
      "valueCr": 20,
      "rationale": "Additional ₹20 Cr investment in battery startup Gegadyne Energy Labs, increasing stake to 24.32% (fully diluted). Gegadyne became associate company.",
      "date": "2023-11-15",
      "source": "MoneyWorks4Me",
      "amAngle": "Valuation",
      "amAngleRationale": "Additional ₹20 Cr investment in battery startup Gegadyne Energy Labs, increasing stake to 24.32% (fully diluted).…"
    },
    {
      "id": "deal-014",
      "type": "PE/VC",
      "parties": [
        "IFB Industries",
        "IFB Industries"
      ],
      "valueCr": 97,
      "rationale": "IFB invested up to ₹97 Cr in equity of IFB Refrigeration Limited (group company). IRL operates refrigerator facility at Ranjangaon, Pune. Commercial production commenced May 2023.",
      "date": "2023-05-15",
      "source": "EquityBulls",
      "amAngle": "Valuation",
      "amAngleRationale": "IFB invested up to ₹97 Cr in equity of IFB Refrigeration Limited (group company). IRL operates refrigerator facility at…"
    },
    {
      "id": "deal-015",
      "type": "M&A",
      "parties": [
        "IFB Industries",
        "GAAL Singapore (IFB subsidiary)"
      ],
      "valueCr": null,
      "rationale": "IFB's wholly-owned subsidiary GAAL established Schmid Automotive & Appliances GmbH in Switzerland for European design and tooling facility.",
      "date": "2024-11-15",
      "source": "ScanX Trade",
      "amAngle": "CDD Opportunity",
      "amAngleRationale": "IFB's wholly-owned subsidiary GAAL established Schmid Automotive & Appliances GmbH in Switzerland for European design…"
    },
    {
      "id": "deal-016",
      "type": "PE/VC",
      "parties": [
        "Havells India",
        "Internal (Self-funded)"
      ],
      "valueCr": 715,
      "rationale": "Cable capacity expansion at Alwar, Rajasthan. Initial ₹375 Cr (Jul 2024) + additional ₹340 Cr (May 2025). Capacity from 32.9 to 41.45 lakh km.",
      "date": "2024-07-15",
      "source": "Wire & Cable India",
      "amAngle": "Valuation",
      "amAngleRationale": "Cable capacity expansion at Alwar, Rajasthan. Initial ₹375 Cr (Jul 2024) + additional ₹340 Cr (May 2025). Capacity from…"
    },
    {
      "id": "deal-017",
      "type": "PE/VC",
      "parties": [
        "Havells India",
        "Internal (Self-funded)"
      ],
      "valueCr": 450,
      "rationale": "Havells greenfield cable plant at Tumakuru, Karnataka commissioned Sep 2024. Additional ₹450 Cr for expansion of higher-sized cable capacity.",
      "date": "2024-09-15",
      "source": "Business Standard",
      "amAngle": "Valuation",
      "amAngleRationale": "Havells greenfield cable plant at Tumakuru, Karnataka commissioned Sep 2024. Additional ₹450 Cr for expansion of…"
    },
    {
      "id": "deal-018",
      "type": "PE/VC",
      "parties": [
        "Havells India",
        "YEIDA / MeitY"
      ],
      "valueCr": 800,
      "rationale": "Havells received LOI for 50-acre land from YEIDA as anchor investor in 200-acre EMC. JV with 5 other companies. Phase-1 ₹800 Cr. MeitY approved Apr 2025.",
      "date": "2025-04-25",
      "source": "CableCommunity",
      "amAngle": "Valuation",
      "amAngleRationale": "Havells received LOI for 50-acre land from YEIDA as anchor investor in 200-acre EMC. JV with 5 other companies. Phase-1…"
    },
    {
      "id": "deal-019",
      "type": "PE/VC",
      "parties": [
        "Havells India",
        "Internal (Self-funded)"
      ],
      "valueCr": 480,
      "rationale": "Approved new refrigerator manufacturing plant at Ghiloth, Rajasthan. 14 lakh unit capacity. Expected operational by Q2 FY27.",
      "date": "2024-11-15",
      "source": "India Infoline",
      "amAngle": "Valuation",
      "amAngleRationale": "Approved new refrigerator manufacturing plant at Ghiloth, Rajasthan. 14 lakh unit capacity. Expected operational by Q2…"
    },
    {
      "id": "deal-020",
      "type": "PE/VC",
      "parties": [
        "Havells India",
        "Havells India"
      ],
      "valueCr": 600,
      "rationale": "Binding term sheet to invest ₹600 Cr in solar PV module manufacturer Goldi Solar as part of ₹1,300 Cr fundraise. Goldi preparing for IPO.",
      "date": "2025-04-14",
      "source": "PV Magazine India",
      "amAngle": "Valuation",
      "amAngleRationale": "Binding term sheet to invest ₹600 Cr in solar PV module manufacturer Goldi Solar as part of ₹1,300 Cr fundraise. Goldi…"
    },
    {
      "id": "deal-021",
      "type": "PE/VC",
      "parties": [
        "Havells India",
        "Havells India (lead) + Nikhil Kamath + others"
      ],
      "valueCr": 600,
      "rationale": "Havells led ₹1,422 Cr growth round in Goldi Solar (Havells share: ₹600 Cr). Other investors: Nikhil Kamath ~₹140 Cr, Ambit, Shahi Exports, SRF.",
      "date": "2025-10-29",
      "source": "Business Standard",
      "amAngle": "Valuation",
      "amAngleRationale": "Havells led ₹1,422 Cr growth round in Goldi Solar (Havells share: ₹600 Cr). Other investors: Nikhil Kamath ~₹140 Cr,…"
    },
    {
      "id": "deal-022",
      "type": "PE/VC",
      "parties": [
        "Havells India",
        "Havells India"
      ],
      "valueCr": 6,
      "rationale": "Acquired 26% stake in Kundan Solar SPV for 15 MWac captive solar plant in Rajasthan. ₹5.63 Cr in phases. 25-year PPA.",
      "date": "2025-11-28",
      "source": "SolarQuarter",
      "amAngle": "Valuation",
      "amAngleRationale": "Acquired 26% stake in Kundan Solar SPV for 15 MWac captive solar plant in Rajasthan. ₹5.63 Cr in phases. 25-year PPA."
    },
    {
      "id": "deal-023",
      "type": "M&A",
      "parties": [
        "Havells India",
        "HPL Group"
      ],
      "valueCr": 130,
      "rationale": "Havells settled trademark dispute with HPL Group, paying ₹129.60 Cr. HPL acknowledged Havells' absolute rights to the 'HAVELLS' trademark since 1971.",
      "date": "2025-11-15",
      "source": "Tracxn",
      "amAngle": "CDD Opportunity",
      "amAngleRationale": "Havells settled trademark dispute with HPL Group, paying ₹129.60 Cr. HPL acknowledged Havells' absolute rights to the…"
    },
    {
      "id": "deal-024",
      "type": "M&A",
      "parties": [
        "Havells India",
        "Whirlpool Corporation (seller)"
      ],
      "valueCr": null,
      "rationale": "Havells entered race to acquire 31% controlling stake in Whirlpool India. Withdrew due to valuation concerns and strategic focus on existing business.",
      "date": "2025-06-20",
      "source": "Business Standard",
      "amAngle": "Valuation",
      "amAngleRationale": "Havells entered race to acquire 31% controlling stake in Whirlpool India. Withdrew due to valuation concerns and…"
    },
    {
      "id": "deal-025",
      "type": "PE/VC",
      "parties": [
        "Havells India",
        "Havells India + SRF Ltd"
      ],
      "valueCr": 34,
      "rationale": "Co-led $4M (~₹34 Cr) funding round in wellness startup Dhun Wellness (Mira Kapoor). Proceeds for expansion to Pune, Hyderabad, Bengaluru.",
      "date": "2026-01-22",
      "source": "StartupNews.fyi",
      "amAngle": "Valuation",
      "amAngleRationale": "Co-led $4M (~₹34 Cr) funding round in wellness startup Dhun Wellness (Mira Kapoor). Proceeds for expansion to Pune,…"
    },
    {
      "id": "deal-026",
      "type": "PE/VC",
      "parties": [
        "Havells India",
        "Govt of India (DPIIT)"
      ],
      "valueCr": null,
      "rationale": "Havells among approved beneficiaries of PLI White Goods scheme for AC and LED manufacturing. Incentives of 4-6% on incremental sales.",
      "date": "2026-02-15",
      "source": "PIB",
      "amAngle": "Valuation",
      "amAngleRationale": "Havells among approved beneficiaries of PLI White Goods scheme for AC and LED manufacturing. Incentives of 4-6% on…"
    },
    {
      "id": "deal-027",
      "type": "M&A",
      "parties": [
        "Symphony",
        "Existing Shareholders"
      ],
      "valueCr": 200,
      "rationale": "Buyback of 10,00,000 equity shares at ₹2,000/share via tender offer. Acceptance ratio ~9% for retail. Promoters participated.",
      "date": "2023-05-17",
      "source": "Business Standard",
      "amAngle": "Valuation",
      "amAngleRationale": "Buyback of 10,00,000 equity shares at ₹2,000/share via tender offer. Acceptance ratio ~9% for retail. Promoters…"
    },
    {
      "id": "deal-028",
      "type": "M&A",
      "parties": [
        "Symphony",
        "Existing Shareholders"
      ],
      "valueCr": 71,
      "rationale": "Buyback of 2,85,600 shares at ₹2,500/share via tender offer. Acceptance ratio ~10% for retail. Return surplus cash to shareholders.",
      "date": "2024-09-02",
      "source": "Chittorgarh.com",
      "amAngle": "Valuation",
      "amAngleRationale": "Buyback of 2,85,600 shares at ₹2,500/share via tender offer. Acceptance ratio ~10% for retail. Return surplus cash to…"
    },
    {
      "id": "deal-029",
      "type": "M&A",
      "parties": [
        "Symphony",
        "Multiple potential buyers"
      ],
      "valueCr": null,
      "rationale": "Board approved divestment of Australian subsidiary (Climate Technologies, revenue ₹185 Cr, negative EBITDA) and Mexican subsidiary (IMPCO, revenue ₹178 Cr). Later shelved — no buyer met valuation expectations.",
      "date": "2025-04-12",
      "source": "TipRanks",
      "amAngle": "Carve-out Advisory",
      "amAngleRationale": "Board approved divestment of Australian subsidiary (Climate Technologies, revenue ₹185 Cr, negative EBITDA) and Mexican…"
    },
    {
      "id": "deal-030",
      "type": "M&A",
      "parties": [
        "Symphony",
        "IMPCO S de R.I. de C.V. (intra-group)"
      ],
      "valueCr": 44,
      "rationale": "Symphony's Chinese subsidiary GSK sold technology know-how and 9 IPRs to IMPCO Mexico for $5.1M (~₹44 Cr). GSK to become debt-free.",
      "date": "2025-04-12",
      "source": "TipRanks",
      "amAngle": "Carve-out Advisory",
      "amAngleRationale": "Symphony's Chinese subsidiary GSK sold technology know-how and 9 IPRs to IMPCO Mexico for $5.1M (~₹44 Cr). GSK to…"
    },
    {
      "id": "deal-031",
      "type": "M&A",
      "parties": [
        "Orient Electric",
        "Ambuja Cements (Adani Group)"
      ],
      "valueCr": 8100,
      "rationale": "CK Birla Group sold 46.8% stake in Orient Cement to Ambuja Cements for ₹8,100 Cr. Capital being reallocated to consumer-centric businesses incl. Orient Electric.",
      "date": "2024-10-22",
      "source": "Business Standard",
      "amAngle": "Valuation",
      "amAngleRationale": "CK Birla Group sold 46.8% stake in Orient Cement to Ambuja Cements for ₹8,100 Cr. Capital being reallocated to…"
    },
    {
      "id": "deal-032",
      "type": "M&A",
      "parties": [
        "Dixon Technologies",
        "Dixon Technologies"
      ],
      "valueCr": 275,
      "rationale": "Dixon acquired 50.1% stake in Ismartu India (Transsion brands: Itel, Infinix, Tecno). CCI approved Jul 18. Tranche 2 (1.7-5.9%) to be acquired in 2026-27.",
      "date": "2024-08-13",
      "source": "MarketScreener",
      "amAngle": "CDD Opportunity",
      "amAngleRationale": "Dixon acquired 50.1% stake in Ismartu India (Transsion brands: Itel, Infinix, Tecno). CCI approved Jul 18. Tranche 2…"
    },
    {
      "id": "deal-033",
      "type": "M&A",
      "parties": [
        "Dixon Technologies",
        "Dixon Technologies (51%) + Vivo India (49%)"
      ],
      "valueCr": null,
      "rationale": "Binding term sheet for JV for OEM manufacturing of smartphones and electronic devices. Dixon holds 51% stake.",
      "date": "2024-12-15",
      "source": "Business Standard",
      "amAngle": "CDD Opportunity",
      "amAngleRationale": "Binding term sheet for JV for OEM manufacturing of smartphones and electronic devices. Dixon holds 51% stake."
    },
    {
      "id": "deal-034",
      "type": "M&A",
      "parties": [
        "Dixon Technologies",
        "Dixon + Signify Innovations (Philips Lighting)"
      ],
      "valueCr": null,
      "rationale": "Binding term sheet for JV focused on OEM business of lighting products and accessories in India.",
      "date": "2025-04-15",
      "source": "Digitimes",
      "amAngle": "CDD Opportunity",
      "amAngleRationale": "Binding term sheet for JV focused on OEM business of lighting products and accessories in India."
    },
    {
      "id": "deal-035",
      "type": "M&A",
      "parties": [
        "Dixon Technologies",
        "Dixon Technologies"
      ],
      "valueCr": null,
      "rationale": "Binding term sheet to acquire 51% stake in Q Tech India for manufacturing camera modules and fingerprint modules for mobile, IoT, automotive.",
      "date": "2025-07-16",
      "source": "Business Standard",
      "amAngle": "CDD Opportunity",
      "amAngleRationale": "Binding term sheet to acquire 51% stake in Q Tech India for manufacturing camera modules and fingerprint modules for…"
    },
    {
      "id": "deal-036",
      "type": "PE/VC",
      "parties": [
        "Dixon Technologies",
        "Govt of India (MeitY)"
      ],
      "valueCr": 1527,
      "rationale": "Dixon major PLI beneficiary for mobile phones and IT hardware. Allocation reduced to ₹1,527 Cr from ₹9,000 Cr. Uncertainty about extension post FY26.",
      "date": "2026-02-15",
      "source": "ScanX Trade",
      "amAngle": "Valuation",
      "amAngleRationale": "Dixon major PLI beneficiary for mobile phones and IT hardware. Allocation reduced to ₹1,527 Cr from ₹9,000 Cr.…"
    },
    {
      "id": "deal-037",
      "type": "PE/VC",
      "parties": [
        "Dixon Technologies",
        "Dixon + HKC (China) / India Semiconductor Mission"
      ],
      "valueCr": 25000,
      "rationale": "Planned $2.7-3 billion display fab in Noida. 60,000 substrates/month. Fuelled by India Semiconductor Mission incentives. Production target late Q1/early Q2 FY26.",
      "date": "2026-02-15",
      "source": "Techovedas",
      "amAngle": "Valuation",
      "amAngleRationale": "Planned $2.7-3 billion display fab in Noida. 60,000 substrates/month. Fuelled by India Semiconductor Mission…"
    },
    {
      "id": "deal-038",
      "type": "M&A",
      "parties": [
        "Amber Enterprises",
        "Amber + Ascent-K Circuit (subsidiary)"
      ],
      "valueCr": 6785,
      "rationale": "100 acres for new manufacturing facility near Jewar Airport + 16 acres for Ascent-K PCB unit; 3,000+ direct jobs.",
      "date": "2026-01-19",
      "source": "ScanX Trade",
      "amAngle": "Valuation",
      "amAngleRationale": "100 acres for new manufacturing facility near Jewar Airport + 16 acres for Ascent-K PCB unit; 3,000+ direct jobs."
    },
    {
      "id": "deal-039",
      "type": "PE/VC",
      "parties": [
        "Amber Enterprises",
        "Qualified Institutional Buyers"
      ],
      "valueCr": 1000,
      "rationale": "Raised ~₹1,000 Cr via QIP. Allocated 12,57,861 equity shares at ₹7,950/share to qualified institutional buyers.",
      "date": "2025-09-22",
      "source": "Law.asia",
      "amAngle": "Valuation",
      "amAngleRationale": "Raised ~₹1,000 Cr via QIP. Allocated 12,57,861 equity shares at ₹7,950/share to qualified institutional buyers."
    },
    {
      "id": "deal-040",
      "type": "PE/VC",
      "parties": [
        "Amber Enterprises",
        "Qualified Institutional Buyers"
      ],
      "valueCr": 2500,
      "rationale": "Board approved second QIP to raise up to ₹2,500 Cr with floor price of ₹7,790.88/share.",
      "date": "2025-09-15",
      "source": "ICICI Direct",
      "amAngle": "Valuation",
      "amAngleRationale": "Board approved second QIP to raise up to ₹2,500 Cr with floor price of ₹7,790.88/share."
    },
    {
      "id": "deal-041",
      "type": "PE/VC",
      "parties": [
        "Amber Enterprises (IL JIN)",
        "ChrysCapital (₹1,100 Cr) + InCred Growth Partners + Raptor + Two Infinity"
      ],
      "valueCr": 1200,
      "rationale": "₹1,200 Cr from PE investors for ILJIN Electronics via equity shares and CCPS. Funds for Hosur expansion and PCB capabilities.",
      "date": "2025-09-07",
      "source": "Business Standard",
      "amAngle": "Valuation",
      "amAngleRationale": "₹1,200 Cr from PE investors for ILJIN Electronics via equity shares and CCPS. Funds for Hosur expansion and PCB…"
    },
    {
      "id": "deal-042",
      "type": "M&A",
      "parties": [
        "Amber Enterprises (IL JIN)",
        "IL JIN Electronics India Pvt Ltd"
      ],
      "valueCr": 262,
      "rationale": "ILJIN acquired 60% stake in Power-One Micro Systems (BESS, solar inverters, EV chargers, UPS solutions).",
      "date": "2025-08-05",
      "source": "Angel One",
      "amAngle": "CDD Opportunity",
      "amAngleRationale": "ILJIN acquired 60% stake in Power-One Micro Systems (BESS, solar inverters, EV chargers, UPS solutions)."
    },
    {
      "id": "deal-043",
      "type": "M&A",
      "parties": [
        "Amber Enterprises (IL JIN)",
        "IL JIN Electronics via ILJIN Holding"
      ],
      "valueCr": 404,
      "rationale": "ILJIN acquired ~40.24% controlling stake in Israel-listed Unitronics (1989). 56.24 lakh shares at NIS 27.75/share (₹404 Cr). Expanding Industry 4.0 solutions.",
      "date": "2025-07-27",
      "source": "Business Standard",
      "amAngle": "CDD Opportunity",
      "amAngleRationale": "ILJIN acquired ~40.24% controlling stake in Israel-listed Unitronics (1989). 56.24 lakh shares at NIS 27.75/share (₹404…"
    },
    {
      "id": "deal-044",
      "type": "M&A",
      "parties": [
        "Amber Enterprises (IL JIN)",
        "IL JIN Electronics (India) Pvt Ltd"
      ],
      "valueCr": null,
      "rationale": "Majority stake in Shogini Technoarts — Pune-based PCB manufacturer (est. 1982). Top-5 Indian PCB maker. Revenue ₹391 Cr in FY25. Reducing reliance on external PCB suppliers.",
      "date": "2025-11-14",
      "source": "BusinessToday",
      "amAngle": "CDD Opportunity",
      "amAngleRationale": "Majority stake in Shogini Technoarts — Pune-based PCB manufacturer (est. 1982). Top-5 Indian PCB maker. Revenue ₹391 Cr…"
    },
    {
      "id": "deal-045",
      "type": "M&A",
      "parties": [
        "Amber Enterprises (IL JIN)",
        "IL JIN Electronics"
      ],
      "valueCr": null,
      "rationale": "ILJIN gained control of Stelltek; the joint venture became a subsidiary with Stelltek becoming an ILJIN/Amber step-down subsidiary.",
      "date": "2026-02-15",
      "source": "Tracxn",
      "amAngle": "CDD Opportunity",
      "amAngleRationale": "ILJIN gained control of Stelltek; the joint venture became a subsidiary with Stelltek becoming an ILJIN/Amber step-down…"
    },
    {
      "id": "deal-046",
      "type": "M&A",
      "parties": [
        "TTK Prestige",
        "Public Shareholders"
      ],
      "valueCr": 200,
      "rationale": "Buyback of 16,66,666 equity shares (1.2% equity) at ₹1,200/share via tender offer. 25% premium over market. Acceptance ratio ~11% for retail.",
      "date": "2024-08-27",
      "source": "Chittorgarh.com",
      "amAngle": "Valuation",
      "amAngleRationale": "Buyback of 16,66,666 equity shares (1.2% equity) at ₹1,200/share via tender offer. 25% premium over market. Acceptance…"
    },
    {
      "id": "deal-047",
      "type": "PE/VC",
      "parties": [
        "TTK Prestige",
        "TTK Prestige"
      ],
      "valueCr": 15,
      "rationale": "Investment via CCDs in rural distribution startup. Initial ₹5 Cr with total commitment up to ₹15 Cr. >5% equity on conversion.",
      "date": "2024-06-12",
      "source": "Business Standard",
      "amAngle": "Valuation",
      "amAngleRationale": "Investment via CCDs in rural distribution startup. Initial ₹5 Cr with total commitment up to ₹15 Cr. >5% equity on…"
    },
    {
      "id": "deal-048",
      "type": "PE/VC",
      "parties": [
        "TTK Prestige",
        "Internal (Self-funded)"
      ],
      "valueCr": 500,
      "rationale": "Board approved ₹500 Cr over 3 FYs: ₹300 Cr capex (stainless steel tri-ply, appliances, plant automation) + ₹200 Cr opex (innovation, design, go-to-market).",
      "date": "2025-02-19",
      "source": "Business Standard",
      "amAngle": "Valuation",
      "amAngleRationale": "Board approved ₹500 Cr over 3 FYs: ₹300 Cr capex (stainless steel tri-ply, appliances, plant automation) + ₹200 Cr opex…"
    },
    {
      "id": "deal-049",
      "type": "M&A",
      "parties": [
        "JCHAC (now Bosch Home Comfort India)",
        "Robert Bosch GmbH"
      ],
      "valueCr": null,
      "rationale": "As part of global $8.1B transaction, Bosch acquired Johnson Controls' residential HVAC business incl. 100% of JCH JV (JCI 60% + Hitachi 40%). Indirect control of 74.25% of JCHAC India.",
      "date": "2025-07-31",
      "source": "Sullivan & Cromwell",
      "amAngle": "CDD Opportunity",
      "amAngleRationale": "As part of global $8.1B transaction, Bosch acquired Johnson Controls' residential HVAC business incl. 100% of JCH JV…"
    },
    {
      "id": "deal-050",
      "type": "M&A",
      "parties": [
        "JCHAC (now Bosch Home Comfort India)",
        "Robert Bosch GmbH / Bosch Global Software Technologies"
      ],
      "valueCr": 382,
      "rationale": "SEBI mandatory open offer for 25.75% minority stake (70 lakh shares). Tendering Nov 13-26, 2025. 21.67 lakh shares tendered (31% acceptance). Bosch post-offer holding: ~82.22%.",
      "date": "2025-12-09",
      "source": "SEBI Filing",
      "amAngle": "CDD Opportunity",
      "amAngleRationale": "SEBI mandatory open offer for 25.75% minority stake (70 lakh shares). Tendering Nov 13-26, 2025. 21.67 lakh shares…"
    },
    {
      "id": "deal-051",
      "type": "PE/VC",
      "parties": [
        "JCHAC (now Bosch Home Comfort India)",
        "Govt of India (DPIIT)"
      ],
      "valueCr": null,
      "rationale": "JCHAC selected as PLI beneficiary for White Goods (AC category) in Round 1. Incentives of 4-6% on incremental domestic manufacturing sales.",
      "date": "2026-02-15",
      "source": "PIB",
      "amAngle": "Valuation",
      "amAngleRationale": "JCHAC selected as PLI beneficiary for White Goods (AC category) in Round 1. Incentives of 4-6% on incremental domestic…"
    }
  ],
  "aiPatterns": [
    {
      "pattern": "M&A consolidation wave across consumer durables",
      "confidence": "high",
      "supportingDeals": [
        "deal-001",
        "deal-002",
        "deal-003",
        "deal-004",
        "deal-005"
      ],
      "explanation": "29 M&A transactions tracked across the sector — stake sales, divestitures, and strategic acquisitions indicate ongoing consolidation. Key acquirers actively reshaping category positions."
    },
    {
      "pattern": "PLI-driven capital raises and strategic investments",
      "confidence": "high",
      "supportingDeals": [
        "deal-006",
        "deal-007",
        "deal-009",
        "deal-013",
        "deal-014"
      ],
      "explanation": "22 PE/VC and capital raise transactions linked to PLI capacity expansion, QIPs, and strategic investments. Government incentive structure attracting institutional capital."
    },
    {
      "pattern": "Emerging stress signals triggering ownership changes",
      "confidence": "medium",
      "supportingDeals": [
        "deal-003",
        "deal-005",
        "deal-008",
        "deal-010",
        "deal-029",
        "deal-030"
      ],
      "explanation": "6 transactions flagged for restructuring or carve-out signals — divestitures, failed deals, and promoter stake changes suggest financial stress at select companies."
    },
    {
      "pattern": "Deal activity acceleration in CY2025-26",
      "confidence": "high",
      "supportingDeals": [
        "deal-002",
        "deal-003",
        "deal-004",
        "deal-005",
        "deal-009",
        "deal-011"
      ],
      "explanation": "32 deals since Jan 2025, reflecting heightened M&A and capital markets activity. Industry entering a structural consolidation and investment phase."
    }
  ]
};

export default data;
