import type { SubSectorDeepDiveData } from "../../types/sections";

// Generated by scripts/etl-v1-to-v2-mocks.mjs — 2026-02-22
// Source: consumer-durables-intelligence/assets/js/data.js

const data: SubSectorDeepDiveData = {
  "section": "sub-sector-deep-dive",
  "dataAsOf": "Q3 FY26",
  "lastUpdated": "2026-02-22T00:00:00Z",
  "subSector": "Consumer Durables",
  "costsBreakdown": [
    {
      "costItem": "Raw Materials (Materials + Stock-in-Trade)",
      "sharePct": 64.5,
      "trendVsPrior": "up",
      "notes": "Top quartile: 58.2%, Bottom: 69.1%. Copper +32% YoY driving material costs."
    },
    {
      "costItem": "Employee Cost",
      "sharePct": 8.2,
      "trendVsPrior": "flat",
      "notes": "Top quartile: 5.8%, Bottom: 11.4%. OEM/ODM companies (Dixon, Amber) skew lower."
    },
    {
      "costItem": "Other Expenses (Logistics, Marketing, Overheads)",
      "sharePct": 22.1,
      "trendVsPrior": "up",
      "notes": "Top quartile: 18.5%, Bottom: 25.3%. D2C expansion increasing marketing spend."
    },
    {
      "costItem": "Operating Margin (Residual)",
      "sharePct": 7,
      "trendVsPrior": "flat",
      "notes": "Sector median OPM 7%. Top quartile: 9.7%."
    }
  ],
  "marginLevers": [
    {
      "lever": "Premiumization / Value-Mix Shift",
      "impactBps": 225,
      "feasibility": "medium",
      "explanation": "Top-quartile OPM 9.7% vs bottom-quartile 6.2%. Premium brands (Havells 13.5%, TTK 14.2%) vs mass (Bajaj 3.8%, Butterfly 2.1%). Upselling to premium SKUs lifts ASPs without proportional cost increase."
    },
    {
      "lever": "Backward Integration / Localization",
      "impactBps": 175,
      "feasibility": "low",
      "explanation": "Companies with >35% import dependency (IFB 42%, Whirlpool 38%) face ₹12,500/ton copper exposure. Localization to 80%+ (Havells 82%, Voltas 78%) cuts landed costs 8–12%."
    },
    {
      "lever": "Distribution Rationalization",
      "impactBps": 115,
      "feasibility": "medium",
      "explanation": "Dealer productivity ranges from ₹0.22 Cr (Crompton) to ₹2.33 Cr (Voltas). Bottom quartile has 3–5x room for ROI-per-touchpoint improvement through network pruning and geo-clustering."
    },
    {
      "lever": "Vendor Consolidation",
      "impactBps": 85,
      "feasibility": "high",
      "explanation": "Vendor consolidation index ranges from 45 (IFB) to 82 (Dixon). Companies below 60 (IFB, Butterfly, Orient) overpay 3–5% on input costs from fragmented procurement."
    },
    {
      "lever": "SKU Rationalization",
      "impactBps": 80,
      "feasibility": "high",
      "explanation": "Dixon retiring legacy low-margin lines (Feb 2026). Blue Star launched 150 AC models — high SKU count risks complexity cost. Typical 20% long-tail SKU elimination yields 60–100 bps."
    }
  ],
  "topQuartileAnalysis": [
    {
      "metric": "EBITDA Margin",
      "topQuartileValue": 11.18,
      "medianValue": 9.6,
      "bottomQuartileValue": 7.43,
      "unit": "%",
      "topPerformers": [
        "Symphony",
        "Crompton Greaves Consumer",
        "TTK Prestige"
      ]
    },
    {
      "metric": "Working Capital Days",
      "topQuartileValue": -5,
      "medianValue": 16,
      "bottomQuartileValue": 35,
      "unit": "days",
      "topPerformers": [
        "Amber Enterprises",
        "Crompton Greaves Consumer",
        "Symphony"
      ]
    },
    {
      "metric": "Return on Capital Employed",
      "topQuartileValue": 25,
      "medianValue": 18,
      "bottomQuartileValue": 14,
      "unit": "%",
      "topPerformers": [
        "Dixon Technologies",
        "Symphony",
        "Blue Star"
      ]
    }
  ]
};

export default data;
