import type { LeadershipGovernanceData } from "../../types/sections";

// Generated by scripts/etl-v1-to-v2-mocks.mjs — 2026-02-22
// Source: consumer-durables-intelligence/assets/js/data.js

const data: LeadershipGovernanceData = {
  "section": "leadership-governance",
  "dataAsOf": "Q3 FY26",
  "lastUpdated": "2026-02-22T00:00:00Z",
  "cxoChanges": [
    {
      "company": "Voltas",
      "role": "Managing Director & CEO",
      "incoming": "Mukundan Menon",
      "outgoing": "Pradeep Bakshi",
      "effectiveDate": "2025-09-01",
      "context": "Pradeep Bakshi chose not to seek reappointment after his term ended Aug 31, 2025. Mukundan Menon (ex-Blue Star, 17 yrs) was MD Designate from Apr 2025, assumed full MD role Sep 1."
    },
    {
      "company": "Voltas",
      "role": "Chief Marketing Officer",
      "incoming": null,
      "outgoing": "Arvinder Singh Pental + 5 others",
      "effectiveDate": "2025-01-22",
      "context": "Top-level exodus: Head of Commercial Refrigeration, marketing chief, strategy head, HR chief, corporate finance head resigned. Linked to HQ relocation from Delhi to Mumbai."
    },
    {
      "company": "Voltas",
      "role": "Chief Marketing Officer",
      "incoming": "Pragya Bijalwan",
      "outgoing": null,
      "effectiveDate": "2025-01-15",
      "context": "New CMO hired from Crompton Greaves Consumer where she was CMO & VP Marketing for ~4 years. Prior experience at HPCL, AkzoNobel, Castrol."
    },
    {
      "company": "Havells India",
      "role": "Senior Leadership",
      "incoming": "Multiple: CPO , CTO , CHRO , Cables President",
      "outgoing": null,
      "effectiveDate": "2025-08-01",
      "context": "Systematic CXO bench-building: Sandeep Bhargava (CPO, ex-Polycab), Dipesh Shah (CTO, ex-Samsung R&D 32 yrs), Preemita Singh (CHRO, ex-Hero FinCorp), Manjit Sethi (President Cables)."
    },
    {
      "company": "Bajaj Electricals",
      "role": "Managing Director & CEO",
      "incoming": "Anuj Poddar",
      "outgoing": null,
      "effectiveDate": "2024-09-30",
      "context": "Poddar resigned after 5.5 yrs to pursue external opportunity. Stock dropped ~7%. Company operated without full-time MD/CEO from Oct 2024 through Apr 2025 — 6-month leadership vacuum."
    },
    {
      "company": "Bajaj Electricals",
      "role": "Managing Director & CEO",
      "incoming": "Sanjay Sachdeva",
      "outgoing": null,
      "effectiveDate": "2025-04-15",
      "context": "Sachdeva joined from Unilever Japan (MD & CEO). 30+ yrs at HUL across global markets. Significant pivot to FMCG-background leader for a durables company."
    },
    {
      "company": "Bajaj Electricals",
      "role": "Chief Financial Officer",
      "incoming": null,
      "outgoing": "E.C. Prasad",
      "effectiveDate": "2025-12-31",
      "context": "CFO resigned to pursue external opportunity. Board advanced relieving date by a month. Dual C-suite turnover (CEO + CFO) within 12 months."
    },
    {
      "company": "IFB Industries",
      "role": "Managing Director & CEO",
      "incoming": "Raj Shankar Ray",
      "outgoing": null,
      "effectiveDate": "2026-01-19",
      "context": "Professional CEO of core Home Appliances Division resigned citing personal reasons (90-day notice). Leaves division without professional head during critical competitive period."
    },
    {
      "company": "Orient Electric",
      "role": "Managing Director & CEO",
      "incoming": "Ravindra Singh Negi",
      "outgoing": null,
      "effectiveDate": "2024-05-31",
      "context": "Negi recruited from Bajaj Electricals (COO, Consumer Products). Second MD change within 11 months — Khetrapal (Jul 2023) then Negi (May 2024). Signals strategic uncertainty at CK Birla Group level."
    },
    {
      "company": "Orient Electric",
      "role": "Chief Financial Officer",
      "incoming": "Arvind Vats",
      "outgoing": "Saibal Sengupta",
      "effectiveDate": "2025-01-01",
      "context": "Smooth CFO succession. New CFO appointed with dual CFO + Chief Risk Officer mandate — signals elevated governance focus. 30 yrs experience including IPO & ERM."
    },
    {
      "company": "Symphony",
      "role": "Chief Marketing Officer",
      "incoming": "Gaurav Sarda",
      "outgoing": "Anuj Arora",
      "effectiveDate": "2025-02-06",
      "context": "Marketing leadership transition at CXO level. Brief overlap period. Founder-promoter CMD Achal Bakeri remains firmly in control."
    }
  ],
  "boardReshuffles": [
    {
      "company": "Blue Star",
      "change": "Promoter Vir Advani elevated to Chairman & MD, succeeding Shailesh Haribhakti (retired Mar 31, 2024). Advani family consolidation of control.",
      "date": "2024-04-01",
      "significance": "low"
    },
    {
      "company": "Crompton Greaves Consumer",
      "change": "Non-Executive Vice Chairman Shantanu Khosla ceased to be Director upon term completion. Marks end of founding professional management era post-Advent International PE exit.",
      "date": "2025-12-31",
      "significance": "medium"
    },
    {
      "company": "Crompton Greaves Consumer",
      "change": "Long-serving Independent Director (10 yrs, 2 terms) reclassified to Non-Independent and appointed Chairman. Governance concern: independent-to-non-independent transition.",
      "date": "2025-09-18",
      "significance": "medium"
    },
    {
      "company": "Bajaj Electricals",
      "change": "EPC/Power T&D demerged into Bajel Projects Ltd. Shekhar Bajaj chairs both entities — governance complexity with overlapping leadership.",
      "date": "2025-02-01",
      "significance": "medium"
    },
    {
      "company": "V-Guard Industries",
      "change": "Founder stepped down at age 75 to focus on philanthropy. Son Mithun K. Chittilappilly continues as MD (since 2012). Clean generational transition.",
      "date": "2025-03-31",
      "significance": "low"
    },
    {
      "company": "IFB Industries",
      "change": "Founder-Chairman Bijon Nag passed away at 82. First-ever generational leadership transition. Son Bikramjit Nag redesignated as Executive Chairman & MD from Feb 1, 2024.",
      "date": "2024-01-28",
      "significance": "high"
    },
    {
      "company": "Dixon Technologies",
      "change": "SES proxy advisory flagged: combining Executive Director and Chairman \"blurs demarcation between Board and Management\" during AGM re-appointment resolution.",
      "date": "2025-09-01",
      "significance": "medium"
    },
    {
      "company": "Amber Enterprises",
      "change": "Board restructuring: Jasbir Singh holds 4 titles (Chairman/ED/WTD/CEO). Daljit Singh appointed as ED/WTD/MD. 3 new executive directors added. Heavy promoter-family board loading.",
      "date": "2025-06-01",
      "significance": "medium"
    },
    {
      "company": "TTK Prestige",
      "change": "Died suddenly just 6 months after stepping down. Accelerates weight on new leadership (Raghunathan, Dr. Mukund, MD Vijayaraghavan) to demonstrate independent strategic capability.",
      "date": "2025-10-09",
      "significance": "high"
    },
    {
      "company": "Butterfly Gandhimathi",
      "change": "MD Rangarajan Sriram stepped down. Instead of appointing new MD, company appointed Sagar as \"Manager & CBO\" — deliberate governance downgrade signaling Crompton's tighter control post-failed merger (Oct 2023).",
      "date": "2024-06-14",
      "significance": "high"
    }
  ],
  "promoterStakeChanges": [
    {
      "company": "Whirlpool of India",
      "promoterGroup": "Whirlpool Corp (parent sold 11.23% stake)",
      "previousPct": 11.23,
      "currentPct": 14,
      "changePct": 2.77,
      "context": "Parent sold 11.23% via block deal at ₹1,030/share (14% discount), raising ₹1,489 Cr. Holding dropped from ~51% to ~39.77%. Target: reduce to ~20% by H1 2026. Buyers: EQT, Bain Capital.",
      "amServiceLineImplication": "Highest priority: potential acquisition candidate as parent moves to minority. PE firms circling. Standalone strategy, brand/tech licensing, MBO/strategic buyer advisory."
    },
    {
      "company": "Dixon Technologies",
      "promoterGroup": "Sunil Vachani (sold 2.77% stake for ₹2,221 Cr)",
      "previousPct": 2.77,
      "currentPct": 5.34,
      "changePct": 2.57,
      "context": "Executive Chairman sold 2.77% via open market, personal holding dropped from 5.34% to 2.57%. Combined with governance flag on dual Chairman-ED role.",
      "amServiceLineImplication": "Promoter reducing stake while holding dual Chairman-ED role. Board structure advisory, promoter communication strategy."
    },
    {
      "company": "TTK Prestige",
      "promoterGroup": "T.T. Jagannathan (stepped down as Chairman after 50 yrs)",
      "previousPct": 70.52,
      "currentPct": 70.52,
      "changePct": 0,
      "context": "Voluntarily stepped down to facilitate promoter succession. T.T. Raghunathan (brother) became Chairman. Dr. Mukund T.T. (next gen) became Vice Chairman. Jagannathan made Chairman Emeritus.",
      "amServiceLineImplication": "Generational transition — advisory on family governance framework, professional management empowerment."
    },
    {
      "company": "Bosch Home Comfort (JCHAC)",
      "promoterGroup": "Robert Bosch GmbH (acquired 74.2% stake)",
      "previousPct": 74.2,
      "currentPct": 25.75,
      "changePct": -48.45,
      "context": "Bosch acquired 74.2% from Johnson Controls-Hitachi as part of global $8B deal — largest in Bosch history. Open offer for remaining 25.75%. Complete change of promoter/ownership.",
      "amServiceLineImplication": "Post-acquisition integration advisory: brand transition (Hitachi to Bosch), supply chain realignment, cultural integration (Japanese to German). Q3 loss during restructuring."
    }
  ],
  "auditorFlags": [],
  "aiRiskFlags": [
    {
      "company": "Voltas",
      "riskType": "CXO Exodus Risk",
      "confidence": "high",
      "explanation": "Loss of institutional knowledge across 6+ functions simultaneously. Talent retention strategy and succession planning advisory needed."
    },
    {
      "company": "Bajaj Electricals",
      "riskType": "CEO Change Risk",
      "confidence": "high",
      "explanation": "Leadership vacuum during post-demerger period. Advisory on strategy continuity, interim governance, and succession planning."
    },
    {
      "company": "Bajaj Electricals",
      "riskType": "CFO Exit Risk",
      "confidence": "high",
      "explanation": "CFO exit within months of new CEO joining — possible misalignment. Interim CFO services, financial strategy alignment advisory."
    },
    {
      "company": "IFB Industries",
      "riskType": "Governance Flag Risk",
      "confidence": "high",
      "explanation": "Post-founder transition — highest-impact advisory moment. Succession formalization, professional management induction, strategic review."
    },
    {
      "company": "IFB Industries",
      "riskType": "CEO Change Risk",
      "confidence": "high",
      "explanation": "Triple trigger: founder death + chairman power concentration + professional CEO exit from core division. Interim CEO placement, operational continuity review."
    },
    {
      "company": "Orient Electric",
      "riskType": "CEO Change Risk",
      "confidence": "high",
      "explanation": "Rapid MD turnover suggests strategic realignment. Operational acceleration, category expansion, group-level governance advisory."
    },
    {
      "company": "Whirlpool of India",
      "riskType": "Promoter Stake Change Risk",
      "confidence": "high",
      "explanation": "Highest priority: potential acquisition candidate as parent moves to minority. PE firms circling. Standalone strategy, brand/tech licensing, MBO/strategic buyer advisory."
    },
    {
      "company": "TTK Prestige",
      "riskType": "Governance Flag Risk",
      "confidence": "high",
      "explanation": "Post-founder death — most critical advisory moment. Strategic review, board governance strengthening, continuity of transformation agenda."
    },
    {
      "company": "Butterfly Gandhimathi",
      "riskType": "Governance Flag Risk",
      "confidence": "high",
      "explanation": "Governance downgrade (MD to Manager) suggests Crompton running Butterfly as division. Minority shareholder governance, integration/divestiture strategy advisory."
    },
    {
      "company": "Bosch Home Comfort (JCHAC)",
      "riskType": "Ownership Change Risk",
      "confidence": "high",
      "explanation": "Post-acquisition integration advisory: brand transition (Hitachi to Bosch), supply chain realignment, cultural integration (Japanese to German). Q3 loss during restructuring."
    }
  ],
  "governanceRiskScores": [
    {
      "company": "Voltas",
      "score": "red",
      "factors": [
        "Pradeep Bakshi chose not to seek reappointment after his term ended Aug 31, 2025. Mukundan Menon…",
        "Top-level exodus: Head of Commercial Refrigeration, marketing chief, strategy head, HR chief,…",
        "New CMO hired from Crompton Greaves Consumer where she was CMO & VP Marketing for ~4 years. Prior…"
      ],
      "amServiceLine": "Turnaround & Restructuring Advisory"
    },
    {
      "company": "Blue Star",
      "score": "amber",
      "factors": [
        "Promoter Vir Advani elevated to Chairman & MD, succeeding Shailesh Haribhakti (retired Mar 31,…",
        "MD Thiagarajan reappointed for final term (Apr 2026 - May 2027, retiring at 70). Mohit Sud (ex-HUL,…"
      ],
      "amServiceLine": "Governance & Risk Advisory"
    },
    {
      "company": "Crompton Greaves Consumer",
      "score": "amber",
      "factors": [
        "Non-Executive Vice Chairman Shantanu Khosla ceased to be Director upon term completion. Marks end…",
        "Long-serving Independent Director (10 yrs, 2 terms) reclassified to Non-Independent and appointed…"
      ],
      "amServiceLine": "Governance & Risk Advisory"
    },
    {
      "company": "Havells India",
      "score": "green",
      "factors": [
        "Systematic CXO bench-building: Sandeep Bhargava (CPO, ex-Polycab), Dipesh Shah (CTO, ex-Samsung R&D…"
      ],
      "amServiceLine": "Growth Strategy"
    },
    {
      "company": "Bajaj Electricals",
      "score": "red",
      "factors": [
        "Poddar resigned after 5.5 yrs to pursue external opportunity. Stock dropped ~7%. Company operated…",
        "Sachdeva joined from Unilever Japan (MD & CEO). 30+ yrs at HUL across global markets. Significant…",
        "CFO resigned to pursue external opportunity. Board advanced relieving date by a month. Dual C-suite…",
        "EPC/Power T&D demerged into Bajel Projects Ltd. Shekhar Bajaj chairs both entities — governance…"
      ],
      "amServiceLine": "Turnaround & Restructuring Advisory"
    },
    {
      "company": "V-Guard Industries",
      "score": "green",
      "factors": [
        "Founder stepped down at age 75 to focus on philanthropy. Son Mithun K. Chittilappilly continues as…"
      ],
      "amServiceLine": "Growth Strategy"
    },
    {
      "company": "IFB Industries",
      "score": "red",
      "factors": [
        "Founder-Chairman Bijon Nag passed away at 82. First-ever generational leadership transition. Son…",
        "Professional CEO of core Home Appliances Division resigned citing personal reasons (90-day notice).…"
      ],
      "amServiceLine": "Turnaround & Restructuring Advisory"
    },
    {
      "company": "Orient Electric",
      "score": "red",
      "factors": [
        "Negi recruited from Bajaj Electricals (COO, Consumer Products). Second MD change within 11 months —…",
        "Smooth CFO succession. New CFO appointed with dual CFO + Chief Risk Officer mandate — signals…"
      ],
      "amServiceLine": "Turnaround & Restructuring Advisory"
    },
    {
      "company": "Whirlpool of India",
      "score": "red",
      "factors": [
        "Parent sold 11.23% via block deal at ₹1,030/share (14% discount), raising ₹1,489 Cr. Holding…"
      ],
      "amServiceLine": "Turnaround & Restructuring Advisory"
    },
    {
      "company": "Dixon Technologies",
      "score": "amber",
      "factors": [
        "Executive Chairman sold 2.77% via open market, personal holding dropped from 5.34% to 2.57%.…",
        "SES proxy advisory flagged: combining Executive Director and Chairman \"blurs demarcation between…"
      ],
      "amServiceLine": "Governance & Risk Advisory"
    },
    {
      "company": "Amber Enterprises",
      "score": "amber",
      "factors": [
        "Board restructuring: Jasbir Singh holds 4 titles (Chairman/ED/WTD/CEO). Daljit Singh appointed as…"
      ],
      "amServiceLine": "Governance & Risk Advisory"
    },
    {
      "company": "TTK Prestige",
      "score": "red",
      "factors": [
        "Voluntarily stepped down to facilitate promoter succession. T.T. Raghunathan (brother) became…",
        "Died suddenly just 6 months after stepping down. Accelerates weight on new leadership (Raghunathan,…"
      ],
      "amServiceLine": "Turnaround & Restructuring Advisory"
    },
    {
      "company": "Butterfly Gandhimathi",
      "score": "red",
      "factors": [
        "MD Rangarajan Sriram stepped down. Instead of appointing new MD, company appointed Sagar as…"
      ],
      "amServiceLine": "Turnaround & Restructuring Advisory"
    },
    {
      "company": "Bosch Home Comfort (JCHAC)",
      "score": "red",
      "factors": [
        "Bosch acquired 74.2% from Johnson Controls-Hitachi as part of global $8B deal — largest in Bosch…"
      ],
      "amServiceLine": "Turnaround & Restructuring Advisory"
    },
    {
      "company": "Symphony",
      "score": "green",
      "factors": [
        "Marketing leadership transition at CXO level. Brief overlap period. Founder-promoter CMD Achal…"
      ],
      "amServiceLine": "Growth Strategy"
    }
  ]
};

export default data;
