import type { MarketPulseData } from "../../types/sections";

// Generated by scripts/etl-v1-to-v2-mocks.mjs — 2026-02-22
// Source: consumer-durables-intelligence/assets/js/data.js

const data: MarketPulseData = {
  "section": "market-pulse",
  "dataAsOf": "Q3 FY26",
  "lastUpdated": "2026-02-22T00:00:00Z",
  "demandSignals": [
    {
      "channel": "Sector Aggregate",
      "signal": "Sector revenue grew 6.6% YoY in Q3 FY26 (vs 11.2% in Q2 FY26). Growth decelerating.",
      "direction": "down",
      "magnitude": "+6.6% YoY",
      "dataConfidence": "Verified"
    },
    {
      "channel": "Volume vs Price",
      "signal": "Volume growth at -1% vs price growth at 8%. Top-line resilience driven by price hikes and premium mix, not genuine volume expansion.",
      "direction": "down",
      "magnitude": "Vol -1% / Price +8%",
      "dataConfidence": "Estimated"
    },
    {
      "channel": "Havells",
      "signal": "Revenue ₹5588 Cr (+14.3% YoY). EBITDA margin 9.2%. Standout. Premiumization + housing demand. Rs 4 dividend.",
      "direction": "up",
      "magnitude": "+14.3% YoY",
      "dataConfidence": "Verified"
    },
    {
      "channel": "Voltas",
      "signal": "Revenue ₹3060 Cr (0% YoY). EBITDA margin 3.8%. 17.9% YTD RAC share. UCP EBIT 3.8% beat (vs 2% expected). Inventory liquidation.",
      "direction": "flat",
      "magnitude": "0% YoY",
      "dataConfidence": "Verified"
    },
    {
      "channel": "Blue Star",
      "signal": "Revenue ₹2925 Cr (+4.2% YoY). EBITDA margin 7.5%. \"Subdued quarter\". Draconian cost-control. BEE channel stuffing.",
      "direction": "down",
      "magnitude": "+4.2% YoY",
      "dataConfidence": "Verified"
    },
    {
      "channel": "Crompton",
      "signal": "Revenue ₹1898 Cr (+7% YoY). EBITDA margin 10.3%. ECD +8%, lighting +7%. Butterfly +100 bps. 2 price hike rounds planned.",
      "direction": "flat",
      "magnitude": "+7% YoY",
      "dataConfidence": "Verified"
    },
    {
      "channel": "Urban Premium",
      "signal": "Urban premium demand Double-digit growth. Home improvement boom: ₹3 lakh crore market, 9-10% CAGR to ₹4 lakh crore by 2030.",
      "direction": "up",
      "magnitude": "Double-digit",
      "dataConfidence": "Management Guidance Interpretation"
    },
    {
      "channel": "Rural Volume",
      "signal": "Rural volume recovery: \"Fits and starts\". Growth driver: Price hikes + premium mix, NOT genuine volume expansion.",
      "direction": "flat",
      "magnitude": "Fits and starts",
      "dataConfidence": "Estimated"
    }
  ],
  "inputCosts": [
    {
      "commodity": "Copper",
      "trend": "up",
      "qoqChange": 0.039,
      "yoyChange": 0.257,
      "amImplication": "CRITICAL: 150K ton global shortfall. AI data centers consuming 1.1M tonnes by 2030."
    },
    {
      "commodity": "Steel (HR Coil)",
      "trend": "up",
      "qoqChange": 0.061,
      "yoyChange": 0.195,
      "amImplication": "MEDIUM: 3-year safeguard duty. Domestic mills hiking. Washing machines, fridges hit."
    },
    {
      "commodity": "Aluminum",
      "trend": "up",
      "qoqChange": 0.027,
      "yoyChange": 0.139,
      "amImplication": "HIGH: China 45M ton cap. Hindalco/Novelis EBITDA erosion from US data center electricity."
    },
    {
      "commodity": "Polymer/Plastics",
      "trend": "up",
      "qoqChange": 0.019,
      "yoyChange": 0.08,
      "amImplication": "Index at 108 (base 100)."
    }
  ],
  "inputCostHistory": [
    {
      "period": "Q3 FY23",
      "Copper": 95,
      "Steel": 96,
      "Aluminum": 96,
      "Polymer": 97
    },
    {
      "period": "Q4 FY23",
      "Copper": 104,
      "Steel": 100,
      "Aluminum": 101,
      "Polymer": 99
    },
    {
      "period": "Q1 FY24",
      "Copper": 99,
      "Steel": 102,
      "Aluminum": 98,
      "Polymer": 101
    },
    {
      "period": "Q2 FY24",
      "Copper": 96,
      "Steel": 98,
      "Aluminum": 95,
      "Polymer": 99
    },
    {
      "period": "Q3 FY24",
      "Copper": 100,
      "Steel": 100,
      "Aluminum": 97,
      "Polymer": 100
    },
    {
      "period": "Q4 FY24",
      "Copper": 104,
      "Steel": 96,
      "Aluminum": 100,
      "Polymer": 102
    },
    {
      "period": "Q1 FY25",
      "Copper": 115,
      "Steel": 95,
      "Aluminum": 106,
      "Polymer": 103
    },
    {
      "period": "Q2 FY25",
      "Copper": 108,
      "Steel": 91,
      "Aluminum": 104,
      "Polymer": 101
    },
    {
      "period": "Q3 FY25",
      "Copper": 105,
      "Steel": 87,
      "Aluminum": 101,
      "Polymer": 100
    },
    {
      "period": "Q4 FY25",
      "Copper": 112,
      "Steel": 91,
      "Aluminum": 103,
      "Polymer": 102
    },
    {
      "period": "Q1 FY26",
      "Copper": 120,
      "Steel": 95,
      "Aluminum": 108,
      "Polymer": 104
    },
    {
      "period": "Q2 FY26",
      "Copper": 127,
      "Steel": 98,
      "Aluminum": 112,
      "Polymer": 106
    },
    {
      "period": "Q3 FY26",
      "Copper": 132,
      "Steel": 104,
      "Aluminum": 115,
      "Polymer": 108
    }
  ],
  "marginOutlook": "Sector average EBITDA margin at 9.5% in Q3 FY26 (vs 9.4% QoQ). Top quartile: 11.2%, bottom quartile: 7.6%. Copper at $12,500/ton forecast creates 200-250 bps gross margin pressure. Steel safeguard duty adds ₹3,500-4,000/ton. Companies with backward integration (Havells, V-Guard) better insulated.",
  "channelMix": [
    {
      "channel": "General Trade",
      "currentSharePct": 43.5,
      "previousSharePct": 45.6,
      "trend": "down"
    },
    {
      "channel": "Modern Trade",
      "currentSharePct": 19.1,
      "previousSharePct": 20,
      "trend": "down"
    },
    {
      "channel": "E-Commerce",
      "currentSharePct": 24.3,
      "previousSharePct": 21.9,
      "trend": "up"
    },
    {
      "channel": "Direct-to-Consumer",
      "currentSharePct": 7.8,
      "previousSharePct": 7,
      "trend": "up"
    }
  ],
  "amThoughtLeadership": {
    "title": "Consumer Durables Industry: Navigating Commodity Headwinds and Premiumization",
    "summary": "Sector resilience driven by premiumization and distribution expansion, but genuine volume recovery remains elusive. Companies with backward integration and strong D2C channels best positioned.",
    "url": "https://www.alvarezandmarsal.com/insights",
    "source": "Alvarez & Marsal"
  },
  "policyTracker": [
    {
      "policy": "PLI Rs 1,004 Cr (FY26-27)",
      "status": "active",
      "impact": "Sustains localization. Advantage to backward-integrated players.",
      "affectedCompanies": [
        "ACs & LED"
      ]
    },
    {
      "policy": "Rs 40,000 Cr Electronics Scheme",
      "status": "active",
      "impact": "De-risks supply chain. Accelerates smart tech integration.",
      "affectedCompanies": [
        "Smart Appliances"
      ]
    },
    {
      "policy": "BCD Microwave Parts Exemption",
      "status": "active",
      "impact": "Reduces BoM cost. Encourages global component JVs.",
      "affectedCompanies": [
        "Kitchen Appliances"
      ]
    },
    {
      "policy": "BEE Norms (Jan 1, 2026)",
      "status": "active",
      "impact": "AC +5-10%, Fridge +3-5% price hikes. Channel stuffing. Margin compression.",
      "affectedCompanies": [
        "ACs & Fridges"
      ]
    },
    {
      "policy": "Steel Safeguard Duty (3-yr)",
      "status": "active",
      "impact": "Rs 3,500-4,000/ton cumulative hikes. Washing machines, fridges hit.",
      "affectedCompanies": [
        "White Goods"
      ]
    },
    {
      "policy": "BESS Duty Exemptions",
      "status": "active",
      "impact": "Lowers capex for sustainable tech. V-Guard, Havells benefit.",
      "affectedCompanies": [
        "Inverters & Solar"
      ]
    }
  ],
  "seasonalPatterns": [
    {
      "pattern": "Summer AC & Cooler Surge",
      "timing": "March-June",
      "implication": "AC demand peaks at 160 index (vs 100 avg) in May. Pre-summer stocking starts February. Air cooler peaks at 170 in May."
    },
    {
      "pattern": "Festival Season Appliance Demand",
      "timing": "October-November",
      "implication": "Washing machine demand rises to 110 index Oct-Nov. Water heater peaks at 150 in Jan. Festival offers drive conversion."
    },
    {
      "pattern": "Fan Season Overlap",
      "timing": "March-June",
      "implication": "Fan demand peaks at 155 in May, closely tracking AC season. BLDC premium fans driving ASP uplift."
    }
  ]
};

export default data;
