import type { OperationalIntelligenceData } from "../../types/sections";

// Generated by scripts/etl-v1-to-v2-mocks.mjs — 2026-02-22
// Source: consumer-durables-intelligence/assets/js/data.js

const data: OperationalIntelligenceData = {
  "section": "operational-intelligence",
  "dataAsOf": "Q3 FY26",
  "lastUpdated": "2026-02-22T00:00:00Z",
  "supplyChainSignals": [
    {
      "company": "Whirlpool of India",
      "signal": "Import dependency 25% — localization at 75%, capacity utilization 78%",
      "impact": "neutral",
      "details": "Contract manufacturing: 5%. Vendor consolidation index: 70/100. After-sales cost: 3.2% of revenue."
    },
    {
      "company": "Voltas",
      "signal": "Import dependency 28% — localization at 74%, capacity utilization 90%",
      "impact": "neutral",
      "details": "Contract manufacturing: 15%. Vendor consolidation index: 72/100. After-sales cost: 2.5% of revenue."
    },
    {
      "company": "Blue Star",
      "signal": "Import dependency 22% — localization at 78%, capacity utilization 78%",
      "impact": "neutral",
      "details": "Contract manufacturing: 8%. Vendor consolidation index: 75/100. After-sales cost: 2% of revenue."
    },
    {
      "company": "Crompton Greaves Consumer",
      "signal": "Import dependency 18% — localization at 82%, capacity utilization 76%",
      "impact": "positive",
      "details": "Contract manufacturing: 18%. Vendor consolidation index: 65/100. After-sales cost: 1.8% of revenue."
    },
    {
      "company": "Bajaj Electricals",
      "signal": "Import dependency 35% — localization at 65%, capacity utilization 68%",
      "impact": "neutral",
      "details": "Contract manufacturing: 35%. Vendor consolidation index: 48/100. After-sales cost: 3.5% of revenue."
    },
    {
      "company": "V-Guard Industries",
      "signal": "Import dependency 15% — localization at 85%, capacity utilization 80%",
      "impact": "positive",
      "details": "Contract manufacturing: 15%. Vendor consolidation index: 74/100. After-sales cost: 2.2% of revenue."
    },
    {
      "company": "IFB Industries",
      "signal": "Import dependency 35% — localization at 65%, capacity utilization 62%",
      "impact": "neutral",
      "details": "Contract manufacturing: 5%. Vendor consolidation index: 55/100. After-sales cost: 4% of revenue."
    },
    {
      "company": "Havells India",
      "signal": "Import dependency 12% — localization at 88%, capacity utilization 87%",
      "impact": "positive",
      "details": "Contract manufacturing: 8%. Vendor consolidation index: 82/100. After-sales cost: 1.5% of revenue."
    },
    {
      "company": "Symphony",
      "signal": "Import dependency 45% — localization at 55%, capacity utilization 70%",
      "impact": "negative",
      "details": "Contract manufacturing: 100%. Vendor consolidation index: 78/100. After-sales cost: 1.2% of revenue."
    },
    {
      "company": "Orient Electric",
      "signal": "Import dependency 22% — localization at 78%, capacity utilization 73%",
      "impact": "neutral",
      "details": "Contract manufacturing: 20%. Vendor consolidation index: 68/100. After-sales cost: 2% of revenue."
    },
    {
      "company": "Dixon Technologies",
      "signal": "Import dependency 42% — localization at 58%, capacity utilization 88%",
      "impact": "negative",
      "details": "Contract manufacturing: 0%. Vendor consolidation index: 80/100. After-sales cost: 0.8% of revenue."
    },
    {
      "company": "Amber Enterprises",
      "signal": "Import dependency 28% — localization at 72%, capacity utilization 85%",
      "impact": "neutral",
      "details": "Contract manufacturing: 0%. Vendor consolidation index: 78/100. After-sales cost: 1% of revenue."
    },
    {
      "company": "TTK Prestige",
      "signal": "Import dependency 18% — localization at 82%, capacity utilization 75%",
      "impact": "positive",
      "details": "Contract manufacturing: 10%. Vendor consolidation index: 72/100. After-sales cost: 1.8% of revenue."
    },
    {
      "company": "Butterfly Gandhimathi Appliances",
      "signal": "Import dependency 20% — localization at 80%, capacity utilization 73%",
      "impact": "positive",
      "details": "Contract manufacturing: 20%. Vendor consolidation index: 58/100. After-sales cost: 2.2% of revenue."
    },
    {
      "company": "Johnson Controls-Hitachi Air Conditioning India",
      "signal": "Import dependency 45% — localization at 55%, capacity utilization 55%",
      "impact": "negative",
      "details": "Contract manufacturing: 10%. Vendor consolidation index: 68/100. After-sales cost: 2.5% of revenue."
    }
  ],
  "manufacturingCapacity": [
    {
      "company": "V-Guard Industries",
      "facility": "Sunflame Vapi factory live — kitchen appliance capacity",
      "action": "expansion",
      "investmentCr": null,
      "timeline": "TBD"
    },
    {
      "company": "IFB Industries",
      "facility": "Swiss subsidiary Schmid GmbH — European design facility",
      "action": "expansion",
      "investmentCr": null,
      "timeline": "TBD"
    },
    {
      "company": "IFB Industries",
      "facility": "₹97 Cr in IFB Refrigeration — Ranjangaon plant",
      "action": "expansion",
      "investmentCr": 97,
      "timeline": "TBD"
    },
    {
      "company": "Havells India",
      "facility": "₹480 Cr refrigerator plant at Ghiloth Rajasthan",
      "action": "expansion",
      "investmentCr": null,
      "timeline": "Q2 FY27"
    },
    {
      "company": "Havells India",
      "facility": "₹715 Cr cable expansion at Alwar — two phases",
      "action": "expansion",
      "investmentCr": 375,
      "timeline": "TBD"
    },
    {
      "company": "Dixon Technologies",
      "facility": "$2.7-3B display fab facility in Noida",
      "action": "expansion",
      "investmentCr": null,
      "timeline": "TBD"
    },
    {
      "company": "TTK Prestige",
      "facility": "₹500 Cr 3-year capex — stainless steel + automation",
      "action": "expansion",
      "investmentCr": 300,
      "timeline": "TBD"
    },
    {
      "company": "Blue Star",
      "facility": "New assembly line at Sri City plant",
      "action": "expansion",
      "investmentCr": null,
      "timeline": "TBD"
    }
  ],
  "procurementShifts": [
    {
      "category": "Lighting & Electricals",
      "shift": "PLI scheme Round 3 applicant — white goods",
      "affectedCompanies": [
        "Voltas"
      ],
      "impact": "Among 38 applicants in 3rd round of PLI scheme for white goods (ACs & LED lights)."
    },
    {
      "category": "Air Conditioning",
      "shift": "PLI scheme Round 3 applicant — AC manufacturing",
      "affectedCompanies": [
        "Blue Star"
      ],
      "impact": "Among applicants in 3rd PLI round for AC manufacturing value chain expansion."
    },
    {
      "category": "Consumer Durables",
      "shift": "YEIDA Electronics Manufacturing Cluster — ₹800 Cr",
      "affectedCompanies": [
        "Havells India"
      ],
      "impact": "Anchor investor in 200-acre EMC. 50-acre land. Phase-1 ₹800 Cr. MeitY approved Apr 2025."
    }
  ],
  "retailFootprint": [
    {
      "company": "Whirlpool of India",
      "action": "expansion",
      "storeCount": 8500,
      "geography": "Haryana",
      "details": "Dealer network: 8,500 points. Plants: 3. Employees: 4,200."
    },
    {
      "company": "Voltas",
      "action": "expansion",
      "storeCount": 22000,
      "geography": "Maharashtra",
      "details": "Dealer network: 22,000 points. Plants: 4. Employees: 6,800."
    },
    {
      "company": "Blue Star",
      "action": "expansion",
      "storeCount": 6000,
      "geography": "Maharashtra",
      "details": "Dealer network: 6,000 points. Plants: 5. Employees: 5,200."
    },
    {
      "company": "Crompton Greaves Consumer",
      "action": "expansion",
      "storeCount": 15000,
      "geography": "Maharashtra",
      "details": "Dealer network: 15,000 points. Plants: 6. Employees: 3,800."
    },
    {
      "company": "Bajaj Electricals",
      "action": "expansion",
      "storeCount": 12000,
      "geography": "Maharashtra",
      "details": "Dealer network: 12,000 points. Plants: 4. Employees: 3,200."
    },
    {
      "company": "V-Guard Industries",
      "action": "expansion",
      "storeCount": 18000,
      "geography": "Kerala",
      "details": "Dealer network: 18,000 points. Plants: 7. Employees: 4,100."
    },
    {
      "company": "IFB Industries",
      "action": "expansion",
      "storeCount": 4500,
      "geography": "West Bengal",
      "details": "Dealer network: 4,500 points. Plants: 3. Employees: 3,500."
    },
    {
      "company": "Havells India",
      "action": "expansion",
      "storeCount": 40000,
      "geography": "Uttar Pradesh",
      "details": "Dealer network: 40,000 points. Plants: 14. Employees: 9,200."
    },
    {
      "company": "Symphony",
      "action": "expansion",
      "storeCount": 7500,
      "geography": "Gujarat",
      "details": "Dealer network: 7,500 points. Plants: 2. Employees: 1,200."
    },
    {
      "company": "Orient Electric",
      "action": "expansion",
      "storeCount": 11000,
      "geography": "Pan-India",
      "details": "Dealer network: 11,000 points. Plants: 5. Employees: 3,000."
    },
    {
      "company": "TTK Prestige",
      "action": "expansion",
      "storeCount": 55000,
      "geography": "Karnataka",
      "details": "Dealer network: 55,000 points. Plants: 5. Employees: 4,000."
    },
    {
      "company": "Butterfly Gandhimathi Appliances",
      "action": "expansion",
      "storeCount": 20000,
      "geography": "Tamil Nadu",
      "details": "Dealer network: 20,000 points. Plants: 3. Employees: 1,800."
    },
    {
      "company": "Johnson Controls-Hitachi Air Conditioning India",
      "action": "expansion",
      "storeCount": 5000,
      "geography": "Gujarat",
      "details": "Dealer network: 5,000 points. Plants: 2. Employees: 2,000."
    }
  ]
};

export default data;
