/**
 * AMVA-01 through AMVA-05: A&M Value-Add section type definitions.
 *
 * Extends SectionData with a pipeline of advisory engagement opportunities
 * auto-generated by cross-referencing all other section data.
 * Each opportunity is tagged by A&M practice area and pipeline stage.
 */

import type { SectionData } from "./sections";
import type { AMServiceLine } from "./am-theme";
import type { SourceInfo } from "./source";

/** Pipeline stage for an engagement opportunity */
export type PipelineStage = "identified" | "qualified" | "outreach-ready";

/** A single A&M advisory engagement opportunity */
export interface Opportunity {
  /** Unique opportunity identifier */
  id: string;
  /** Canonical company ID */
  companyId: string;
  /** Company display name */
  companyName: string;
  /** Engagement type, e.g. "Turnaround Advisory", "CPI Assessment" */
  engagementType: string;
  /** Estimated engagement size in INR Crore, or null if unknown */
  estimatedSizeCr: number | null;
  /** AMVA-04: Tagged by A&M practice area */
  practiceArea: AMServiceLine;
  /** AMVA-02: Pipeline stage (Identified / Qualified / Outreach-Ready) */
  pipelineStage: PipelineStage;
  /** AMVA-03: Bullet-point evidence supporting this opportunity */
  keyDataPoints: string[];
  /** AMVA-05: Which section(s) sourced this opportunity */
  sourceSection: string;
  /** Source attribution */
  source: SourceInfo;
}

/** Aggregate pipeline summary across all opportunities */
export interface PipelineSummary {
  /** Count of opportunities in "identified" stage */
  identified: number;
  /** Count of opportunities in "qualified" stage */
  qualified: number;
  /** Count of opportunities in "outreach-ready" stage */
  outreachReady: number;
  /** Total estimated engagement value in INR Crore, or null */
  totalEstimatedValueCr: number | null;
  /** Breakdown of opportunity count by A&M practice area */
  byPracticeArea: { practiceArea: AMServiceLine; count: number }[];
}

/** Complete data payload for the A&M Value-Add section */
export interface AMValueAddData extends SectionData {
  /** All advisory engagement opportunities */
  opportunities: Opportunity[];
  /** Aggregate pipeline summary */
  pipeline: PipelineSummary;
}
